name: hareru
description: "Hareru - Smart household account book for Japan"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  go_router: ^15.1.2
  hive_flutter: ^1.1.0
  intl: any
  fl_chart: ^0.69.0
  flutter_local_notifications: ^18.0.0
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.0.0
  timezone: any
  table_calendar: ^3.1.0
  pdf: ^3.11.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  ios: true
  android: false
  image_path: "assets/icon/appicon-1024.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0F172A"
  image: "assets/icon/symbol-color-512.png"
  image_dark: "assets/icon/symbol-white-512.png"
  ios: true
  android: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/fonts/NotoSansJP-Regular.ttf
    - assets/fonts/NotoSansKR-Regular.ttf

  fonts:
    - family: PretendardJP
      fonts:
        - asset: assets/fonts/PretendardJP-Light.otf
          weight: 300
        - asset: assets/fonts/PretendardJP-Regular.otf
          weight: 400
        - asset: assets/fonts/PretendardJP-Medium.otf
          weight: 500
        - asset: assets/fonts/PretendardJP-SemiBold.otf
          weight: 600
        - asset: assets/fonts/PretendardJP-Bold.otf
          weight: 700
