name: hareru
description: "Hareru - Smart household account book for Japan"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.3
  fl_chart: ^0.69.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  cloud_firestore: ^5.6.7
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#4A90D9"
  color_dark: "#1A1A2E"
  ios: true
  android: true

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/splash/

  fonts:
    - family: PretendardJP
      fonts:
        - asset: assets/fonts/PretendardJP-Regular.otf
          weight: 400
        - asset: assets/fonts/PretendardJP-Medium.otf
          weight: 500
        - asset: assets/fonts/PretendardJP-SemiBold.otf
          weight: 600
        - asset: assets/fonts/PretendardJP-Bold.otf
          weight: 700
